swagger: "2.0"
info:
  version: "0.0.1"
  title: UPI Payment HackerEarth Freecharge
host: localhost:3000
basePath: /
schemes:
  - http
  - https
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
    description: |
      The following syntax must be used in the 'Authorization' header :
      "Bearer {token}"
consumes:
  - application/json
produces:
  - application/json

paths:
  /login:
    x-swagger-router-controller: main_controller
    post:
      description: User login. Returns auth token if credentials are correct
      tags:
        - User
      operationId: login
      parameters:
        - name: loginCreds
          in: body
          required: true
          schema:
            $ref: "#/definitions/Login"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/LoginResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/Error"

  /user:
    x-swagger-router-controller: main_controller
    post:
      description: Register a new user
      tags:
        - User
      operationId: register
      parameters:
        - name: user
          in: body
          required: true
          schema:
            $ref: "#/definitions/NewUser"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Success"
        default:
          description: Error
          schema:
            $ref: "#/definitions/Error"

  /upload:
    x-swagger-router-controller: main_controller
    post:
      operationId: upload
      description: 'Upload csv file by current logged in user'
      tags:
        - User
      consumes:
      - multipart/form-data
      parameters:
      - name: file
        in: formData
        required: true
        type: file
      security:
        - Bearer: []
      responses:
        "200":
          description: "Success"
          schema:
            $ref: "#/definitions/Success"
        default:
          description: "Access Denied"
          schema:
              $ref: "#/definitions/Error" 
        

definitions:
  Success:
    required:
      - message
    properties:
      message:
        type: string
  Error:
    required:
      - message
    properties:
      message:
        type: string

  NewUser:
    properties:
      name:
        type: string
      username:
        type: string
      password:
        type: string

  Login:
    properties:
      email:
        type: string
      password:
        type: string

  LoginResponse:
    properties:
      username:
        type: string
      name:
        type: string
      token:
        type: string
   